### ISSUE TITLE
Not installable on 2.15 due to node-waf-requirement

### ISSUE THREAD

**Issue by thewulf00** [kaliber5/ember-cli-bundle-analyzer#19]
I am not able to install the package due to some old dependency inside some of the dependencies.

```
>ember install ember-cli-bundle-analyzer
Command failed: npm install --save-dev --loglevel error ember-cli-bundle-analyzer
Der Befehl "node-waf" ist entweder falsch geschrieben oder konnte nicht gefunden werden.
```

```
>ember -v
ember-cli: 2.15.1
node: 8.12.0
os: win32 x64
```

The reason behind the problem "node-waf" does not exist any more - it has been replaced by "node-gyp" (that is used by the other dependencies in the project).

Is it possible to update some of the requirements to get rid of the node-waf dependency?

**Comment by simonihmig** [comment]
There is no explicit `node-waf` dependency from this package. Likely a Windows issue...

@thewulf00 Did Ember CLI emit an error log, that you could share here?
