### ISSUE TITLE
Needs update to work with TypeScript apps

### ISSUE THREAD

**Issue by richard-viney** [kaliber5/ember-cli-bundle-analyzer#20]
In this project's `index.js` we need additional entries for TypeScript apps, essentially just duplicating what's already there but with a `.ts` extension instead of `.js`.

    'app/app.ts', // app (TS)
    'src/main.ts', // MU (TS)
    'tests/dummy/app/app.ts' // addon dummy app (TS)

**Comment by simonihmig** [comment]
@richard-viney thanks for reporting! Fixed by #23
