### ISSUE TITLE
Remove `ember-cli-*lint`

### ISSUE THREAD

**Issue by txm** [kaliber5/ember-cli-bundle-analyzer#27]
We're trying to move away from ember dev transpiling, is there a way to use `eslint` etc directly?

> In part II we have removed ember-cli-eslint, ember-cli-stylelint, and ember-cli-template-lint. Instead, we are using eslint, stylelint, and ember-template-lint without losing any coverage. This also removes some weight from our ember server command.

https://dockyard.com/blog/2019/06/18/improving-the-ember-dx-part-2-changing-our-toolbelt

**Comment by simonihmig** [comment]
Sorry for the late response... I am not sure exactly what you mean. You try to use ESLint directly in your app? If so, how is this related to this addon?
