### ISSUE TITLE
Triggering Ember CLI rebuild not working reliably

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-cli-bundle-analyzer#5]
For the first request to `_analyze` the middleware lazily enables the stats output in `broccoli-concat` and triggers a rebuild (to generate the stats output for the first time) by `touch`ing `app.js` ([here](https://github.com/simonihmig/ember-cli-bundle-analyzer/blob/e3a1cd01a264a631b08c849863d674d5311f5d73/index.js#L153).

This kinda works, but not always:

* it *does*  work when running `ember s` inside the addon, thus serving `tests/dummy/app` (it touches `tests/dummy/app/app.js`)

* it *does*  work when running inside an app, *and* using `watchman`

* it **does not** work when running inside an app *without*  watchman, i.e. `sane` is using `fs.watch`. Instead of touching the file, I also tried appending new lines, or adding a completely new file. All that works, but it does not trigger a rebuild. If however I touch it outside of the node process, e.g. on the shell or my IDE, it rebuilds as expected. As if it is ignoring file events caused by its own process? Although it does work for the dummy app!? 🤔

This is on OSX btw.

@stefanpenner sorry for pinging you, but I am pulling my hairs out on this, and already lost a few hours trying things out wildly without really having a clue... with all your insider knowledge of Ember CLI, `sane` and stuff, any idea about this?

**Comment by stefanpenner** [comment]
@simonihmig I'm oncall this week, so my time is pretty limited. If you ping me next tuesday, I can carve out some time :).

**Comment by simonihmig** [comment]
@stefanpenner ping! :)
Don't want to steal your time, I just thought maybe this rings a bell? Like any known issues with file watching that you might know of?
