### ISSUE TITLE
Output results to JSON

### ISSUE THREAD

**Issue by caass** [kaliber5/ember-cli-bundle-analyzer#86]
Is there some way to store the results as a JSON file? This would be really helpful for regression testing in CI. After a cursory search it doesn't seem immediately obvious if that's something that's possible at the moment.

**Comment by simonihmig** [comment]
Sorry for the late answer, seems I missed this 😔

This addon builds on top of https://github.com/stefanpenner/broccoli-concat-analyser, which uses the stats features of broccoli-concat (https://github.com/broccolijs/broccoli-concat#debug-usage). So you could either use that raw data, or write some scripts using the programmatic APIs that `broccoli-concat-analyser` offers (for aggregation and/or calculating minified/gzipped sizes). Unfortunately that's not documented really, so you would need to look at the source.

Btw, if you need to just check whether some bundle size budgets have been surpassed in CI, then have a look at this addon I did: https://github.com/kaliber5/ember-cli-bundlesize
